apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata: 
      labels:
        app: configserver
    spec: 
      containers:
        - name: configserver
          image: robindocker/microservice_configserver:1.0.0
          ports:
          - containerPort: 8071
                 
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
spec:
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
