apiVersion: v1
kind: ConfigMap
metadata:
  name: microservicios-configmap
data:
  spring_profiles_active: dev
  spring_config_config_import: configserver:http://configserver-service:8071/
  eureka_client_serviceurl_defaultzone: http://eurekaserver-service:8070/eureka/

